#!/bin/sh

case "$1" in
    start)
        echo "Starting aesd char driver module"

	module="aesdchar"
	device="aesdchar"
	mode="664"

	if grep -1 '^staff:' /etc/group; then
		group="staff"
	else
		group="wheel"
	fi

	insmod "/lib/modules/5.15.18/extra/${module}.ko" $* || exit 1

	#Get major num
	major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

	rm -f /dev/${device}
	mknod /dev/${device} c $major 0
	# ln -sf ${device} /dev/${device}
	chgrp $group /dev/${device}
	chmod $mode /dev/${device}

        ;;
    stop)
        echo "Stopping external modules"
       
	module="aesdchar"
	device="aesdchar"

	rmmod "/lib/modules/5.15.18/extra/${module}.ko" || exit 1

	# Remove stale nodes

	rm -f /dev/${device}

	;;
    *)
        echo "USAGE: $0 {start|stop}"
    exit 1
esac

